- hosts: localhost
  become: true

  vars:
    realm_domain: "ds.damantec.org"

  vars_prompt:
    - name: "requiredForUsability"
      prompt: "Please press enter"
      private: no
    - name: "realm_username"
      prompt: "Domain Username"
      #private: yes
    - name: "realm_password"
      prompt: "Domain Password"
      private: yes

  tasks:
    - include_tasks: tasks/domain-join/domain-join_01_packages.yml
    - include_tasks: tasks/domain-join/domain-join_02_hostname.yml
    - include_tasks: tasks/domain-join/domain-join_03_mkhomedir.yml

    - name: Check if host has joined a realm domain
      command: realm list
      register: realm_output
      failed_when: false

    - name: Determine if host has not joined the realm
      set_fact:
        not_joined_realm: "{{ realm_domain not in realm_output.stdout }}"

    - name: Join realm domain
      command: /bin/bash -c "echo {{ realm_password }} | realm join --user={{ realm_username }} {{ realm_domain }}"
      register: join_output
      no_log: True
      when:
        - not_joined_realm
        - realm_username is defined
        - realm_password is defined

    - name: Display success message
      debug:
        msg: "Join successful!"
      when: 
        - not_joined_realm
        - join_output.rc == 0

    - name: Display error message
      debug:
        msg: "Join failed or already joined"
      when: 
        - not_joined_realm
        - join_output.rc != 0

    - include_tasks: tasks/domain-join/domain-join_04_sssd.yml
    - include_tasks: tasks/domain-join/domain-join_05_sddm.yml









