- hosts: localhost
  become: true

  vars:
    realm_domain: "ds.damantec.org"

  pre_tasks:
    - name: update repositories (Ubuntu)
      apt:
        update_cache: yes
        allow_unauthenticated: yes
      changed_when: false
      when: ansible_distribution == 'Ubuntu'




  tasks:

    - name: Check if host has joined a realm domain
      command: realm list
      register: realm_output
      failed_when: false

    - name: Determine if host has not joined the realm
      set_fact:
        joined_realm: "{{ realm_domain in realm_output.stdout }}"

    - include_tasks: tasks/domain-join/domain-join_01_packages.yml
      when: joined_realm
    - include_tasks: tasks/domain-join/domain-join_02_hostname.yml
      when: joined_realm
    - include_tasks: tasks/domain-join/domain-join_03_mkhomedir.yml
      when: joined_realm
    - include_tasks: tasks/domain-join/domain-join_04_sssd.yml
      when: joined_realm
    - include_tasks: tasks/domain-join/domain-join_05_sddm.yml
      when: joined_realm
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/sudoers.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/general-settings.yml
    - include_tasks: tasks/kde.yml
    - include_tasks: tasks/autofs.yml


#    - include_tasks: tasks/users.yml
#      when: ansible_distribution == 'Ubuntu'
#    - include_tasks: tasks/ubuntu_settings.yml
#      when: ansible_distribution == 'Ubuntu'
#    - include_tasks: tasks/ubuntu_packages.yml
#      when: ansible_distribution == 'Ubuntu'

#    - include_tasks: tasks/ubuntu_cron.yml
#      when: ansible_distribution == 'Ubuntu'
#    - name: Copy installation script for OMZ to machine
#      ansible.builtin.copy:
#        src: files/.user-config.sh
#        dest: /usr/.user-config.sh
#        owner: root
#        group: root
#        mode: '0755'
#    - include_tasks: tasks/ubuntu_oh-my-zsh.yml
#      vars:
#        uname: root
#    - include: tasks/w_kde.yml
#    - include: tasks/w_config-files-st.yml
#    - include: tasks/w_networkshares.yml
