- hosts: localhost
  become: true
  
  pre_tasks:
    - name: update repositories (Ubuntu)
      apt:
        update_cache: yes
        allow_unauthenticated: yes
      changed_when: false
      when: ansible_distribution == 'Ubuntu'

    - name: Conditional Realm Domain Prompt
#      hosts: all
 #     gather_facts: yes

      vars_prompt:
        - name: realm_username
          prompt: "Enter the realm username"
          private: no
          when: not joined_realm

        - name: realm_password
          prompt: "Enter the realm password"
          private: yes
          when: not joined_realm



  tasks:
    - name: Check if host has joined a realm domain
      command: realm list
      register: realm_list

    - name: Set fact for realm joined status
      set_fact:
        joined_realm: "{{ 'ds.damantec.org' in realm_list.stdout }}"
        
    - include_tasks: tasks/domain-join.yml
      #when: "'ds.damantec.org' not in realm_output.stdout"
#    - include_tasks: tasks/users.yml
#      when: ansible_distribution == 'Ubuntu'
#    - include_tasks: tasks/ubuntu_settings.yml
#      when: ansible_distribution == 'Ubuntu'
#    - include_tasks: tasks/ubuntu_packages.yml
#      when: ansible_distribution == 'Ubuntu'

#    - include_tasks: tasks/ubuntu_cron.yml
#      when: ansible_distribution == 'Ubuntu'
#    - name: Copy installation script for OMZ to machine
#      ansible.builtin.copy:
#        src: files/.user-config.sh
#        dest: /usr/.user-config.sh
#        owner: root
#        group: root
#        mode: '0755'
#    - include_tasks: tasks/ubuntu_oh-my-zsh.yml
#      vars:
#        uname: root
#    - include: tasks/w_kde.yml
#    - include: tasks/w_config-files-st.yml
#    - include: tasks/w_networkshares.yml
