- name: Add simple_allow_groups line
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/ds.damantec.org
    option: simple_allow_groups
    value: Domain Admins

- name: Add use_fully_qualified_names line
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/ds.damantec.org
    option: use_fully_qualified_names
    value: 'False'

- name: Add ad_gpo_access_control line to SSSD config
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/ds.damantec.org
    option: ad_gpo_access_control
    value: permissive

- name: Restart SSSD service
  ansible.builtin.service:
    name: sssd
    state: restarted