- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - sssd
    - sssd-tools
    - realmd
    - oddjob
    - oddjob-mkhomedir
    - libnss-sss
    - libpam-sss
    - samba-common
    - samba-common-bin
    - adcli
    - zsh #required since the domain user receives "/bin/zsh" as default shell

  register: package_installation

- name: Display status of package installation
  debug:
    msg: "{{ item.item }} is successfully installed"
  loop: "{{ package_installation.results }}"
  when: item.changed
  loop_control:
    label: "{{ item.item }}"