- name: Add ad_access_filter line
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/ds.damantec.org
    option: ad_access_filter
    value: "(&(objectClass=user)(memberOf=CN=Domain Users,CN=Users,DC=ds,DC=damantec,DC=org))"

- name: Add use_fully_qualified_names line
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/ds.damantec.org
    option: use_fully_qualified_names
    value: 'False'

- name: Add ad_gpo_access_control line to SSSD config
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/ds.damantec.org
    option: ad_gpo_access_control
    value: permissive

- name: Add zsh as default shell to SSSD config
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/ds.damantec.org
    option: default_shell
    value: /usr/bin/zsh

- name: Restart SSSD service
  ansible.builtin.service:
    name: sssd
    state: restarted