- name: install cron job (ansible-pull)
  ansible.builtin.cron:
    name: "ansible provision"
    user: "ansible"
    minute: "10"
    job: "sudo /usr/bin/ansible-pull -o -U https://github.com/WolfgrammJ/ansible-pull-workstations.git workstation.yml --checkout main > /dev/null"
