- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - sssd
    - sssd-tools
    - realmd
    - oddjob
    - oddjob-mkhomedir
    - libnss-sss
    - libpam-sss
    - samba-common
    - samba-common-bin
    - adcli

  register: package_installation

- name: Display status of package installation
  debug:
    msg: "{{ item.item }} is successfully installed"
  loop: "{{ package_installation.results }}"
  when: item.changed
  loop_control:
    label: "{{ item.item }}"

- name: Set hostname (FQDN)
  ansible.builtin.replace:
    path: /etc/hostname
    regexp: '^\s*([^\s].*?)(?:\s*.ds.damantec.org)?(?=\s*$)'
    replace: '\g<1>.ds.damantec.org'

- name: Add DC to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 10.11.0.11 dmt-gau-nas-001.ds.damantec.org dmt-gau-nas-001


################################################
# ChatGPT Solution for joining
################################################

- name: Check if host has joined a realm domain
  command: realm list
  register: realm_output
  changed_when: false
  failed_when: false

- name: Determine if host has not joined the realm
  set_fact:
    not_joined_realm: "{{ 'ds.damantec.org' not in realm_output.stdout }}"

- name: Prompt for realm username
  pause:
    prompt: "Enter the realm username"
  register: username_input
  when: not_joined_realm

- name: Set realm username
  set_fact:
    realm_username: "{{ username_input.user_input }}"
  when: not_joined_realm

- name: Prompt for realm password
  pause:
    prompt: "Enter the realm password"
    private: yes
  register: password_input
  when: not_joined_realm

- name: Set realm password
  set_fact:
    realm_password: "{{ password_input.user_input }}"
  when: not_joined_realm

- name: Debug realm_username
  debug:
    msg: "Realm username: {{ realm_username }}"
  when: not_joined_realm

- name: Debug realm_password
  debug:
    msg: "Realm password: {{ realm_password }}"
  when: not_joined_realm

- name: Join realm domain
  command: realm join --user={{ realm_username }} --password={{ realm_password }} ds.damantec.org
  when: not_joined_realm



################################################
#- name: Join system
#  command: /bin/bash -c "echo {{ realm_password }} | realm join --user={{ realm_username }} ds.damantec.org"
#  register: join_output
#  #no_log: True
#  ignore_errors: yes
#  when: not joined_realm

#- name: Display success message
#  debug:
#    msg: "Join successful!"
#  when: join_output.rc == 0

#- name: Display error message
#  debug:
#    msg: "Join failed or already joined"
#  when: join_output.rc != 0

- name: Enable automatic creation of user's home directory
  become: yes
  ansible.builtin.command: pam-auth-update --enable mkhomedir

- name: Edit SSSD configuration file
  block:
    - name: Add simple_allow_groups line
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/ds.damantec.org
        option: simple_allow_groups
        value: Domain Admins

    - name: Add use_fully_qualified_names line
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/ds.damantec.org
        option: use_fully_qualified_names
        value: 'False'

    - name: Add ad_gpo_access_control line to SSSD config
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/ds.damantec.org
        option: ad_gpo_access_control
        value: permissive 

    - name: copy sudoers file "damantec"
      copy: src=files/sudoers_damantec dest=/etc/sudoers.d/damantec owner=root group=root mode=0440

- name: Restart the SSSD Service
  block:
    - name: Restart SSSD service
      service:
        name: sssd
        state: restarted