- name: Check if host has joined a realm domain
  command: realm list
  register: realm_output
  changed_when: false
  failed_when: false

- name: Prompt for password for user "admin-onboard"
  vars_prompt:
    - name: "bind_password"
      prompt: "Password for the Directory user"
      private: yes
  when: "'ds.damantec.org' not in realm_output.stdout"

- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - sssd
    - sssd-tools
    - realmd
    - oddjob
    - oddjob-mkhomedir
    - libnss-sss
    - libpam-sss
    - samba-common
    - samba-common-bin
    - adcli

  register: package_installation

- name: Display status of package installation
  debug:
    msg: "{{ item.item }} is successfully installed"
  loop: "{{ package_installation.results }}"
  when: item.changed
  loop_control:
    label: "{{ item.item }}"

- name: Set hostname (FQDN)
  ansible.builtin.replace:
    path: /etc/hostname
    regexp: '^\s*([^\s].*?)(?:\s*.ds.damantec.org)?(?=\s*$)'
    replace: '\g<1>.ds.damantec.org'

- name: Add DC to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 10.11.0.11 dmt-gau-nas-001.ds.damantec.org dmt-gau-nas-001

- name: Join system
  command: /bin/bash -c "echo {{ bind_password }} | realm join --user=Administrator ds.damantec.org"
  register: join_output
  #no_log: True
  ignore_errors: yes
  when: "'ds.damantec.org' not in realm_output.stdout"

- name: Display success message
  debug:
    msg: "Join successful!"
  when: join_output.rc == 0

- name: Display error message
  debug:
    msg: "Join failed or already joined"
  when: join_output.rc != 0

- name: Enable automatic creation of user's home directory
  become: yes
  ansible.builtin.command: pam-auth-update --enable mkhomedir

- name: Edit SSSD configuration file
  block:
    - name: Add simple_allow_groups line
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/ds.damantec.org
        option: simple_allow_groups
        value: Domain Admins

    - name: Add use_fully_qualified_names line
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/ds.damantec.org
        option: use_fully_qualified_names
        value: False 

    - name: Add ad_gpo_access_control line to SSSD config
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/ds.damantec.org
        option: ad_gpo_access_control
        value: permissive 

    - name: copy sudoers file "damantec"
      copy: src=files/sudoers_damantec dest=/etc/sudoers.d/damantec owner=root group=root mode=0440

- name: Restart the SSSD Service
  block:
    - name: Restart SSSD service
      service:
        name: sssd
        state: restarted