- name: copy sudoers file "damantec"
  copy:
    src: files/sudoers_damantec
    dest: /etc/sudoers.d/damantec
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s